services:
  db:
    image: postgres:16
    container_name: contacts-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: contacts-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: